name: Go CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Download dependencies
        run: go mod tidy && go mod download

      - name: Verify build (sanity check)
        run: go build ./...

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

      - name: Run golangci-lint
        run: |
          golangci-lint run \
            --timeout 5m \
            --modules-download-mode=mod \
            --max-issues-per-linter=0 \
            --max-same-issues=0 \
            ./...
