name: Go Lint Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  golangci-lint:
    name: Run golangci-lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.59.0
          echo "$GOPATH/bin" >> $GITHUB_PATH

      - name: Setup Go modules
        run: go mod tidy && go mod download

      - name: Run golangci-lint
        run: |
          golangci-lint run --timeout 5m --max-issues-per-linter=0 --max-same-issues=0
